---
# vars file for /home/gelbcke/ansible-aws/
profile_name: ansible-deploy
sec_gp_name: default-ansible
instance_type: t2.micro
image_id: ami-08ae71fd7f1449df1
key_name: ansible-live
region_id: sa-east-1
count: 1
